# -*- coding: utf-8 -*-
"""Proyecto_Final-DSII-Esteban_Tomas_Sanabria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb3CA_hQ-gbBwYeIxt9WOhK4b1dYa2kw

# **Preentrega Proyecto Final: Análisis de Datos en el Mercado Aeronáutico**

## **Título del Proyecto: Análisis y Visualización de Datos en el Mercado Aeronáutico.**

---

#### **Abstracto y Motivación**
Este análisis explora la composición y características de aeronaves comerciales a nivel mundial, utilizando datos obtenidos mediante una API pública de aviación.

El objetivo es comprender las tendencias de flota, edad promedio por modelo y tecnologías de propulsión más utilizadas.  

---

#### **Audiencia**
- Fabricantes y operadores aeronáuticos.  
- Analistas del mercado aeronáutico y de mantenimiento.  
- Instituciones académicas e ingenieros interesados en la industria del transporte aéreo.

---

#### **Datos de Entrega**
*   Docente: Joaquin Salas.

*   Tutor: Federico Gravina.

*   Alumno: Esteban Tomás Sanabria.

*   Fecha Preentrega: 21/10/2025.

---

# **1 - Introducción del Proyecto:**

El presente proyecto tiene como objetivo explorar y analizar un conjunto de datos provenientes de una API pública de aviación, que proporciona información técnica y operativa de aeronaves registradas a nivel mundial.  

La fuente de datos incluye atributos clave tales como el modelo, línea de producción, número de motores, tipo de propulsión, edad promedio de la aeronave, estado operativo, fecha de entrega y propietario.  

Mediante el uso del lenguaje Python y bibliotecas como Pandas, Seaborn y Matplotlib, se desarrolla un análisis exploratorio orientado a identificar tendencias, patrones y relaciones dentro del parque aeronáutico global.

El propósito central es transformar datos crudos obtenidos por la API en insights significativos sobre la evolución tecnológica, la antigüedad promedio de la flota y la distribución de los principales modelos comerciales.

Este estudio permite a fabricantes, operadores y analistas del sector aeronáutico comprender la dinámica de la flota mundial, detectar oportunidades de renovación tecnológica y optimizar decisiones relacionadas con mantenimiento, inversión y planificación operativa.

A lo largo del análisis se busca responder las siguientes preguntas de interés:

* ¿Cuáles son las líneas de producción más representadas en la flota global?  

* ¿Qué tipos de motor predominan en las aeronaves actuales?  

* ¿Cómo varía la edad promedio de las aeronaves según su modelo o fabricante?  

* ¿Se observa una tendencia de renovación de flota en los últimos años?  

* ¿Existen diferencias en el estado operativo de las aeronaves según su línea de producción?

* ¿Cómo ha evolucionado la entrega de aeronaves a lo largo del tiempo?  

En etapas posteriores, este análisis podrá complementarse con modelos de Machine Learning orientados a la predicción de la vida útil o edad operativa de una aeronave a partir de sus características técnicas y de fabricación.

# **2 - Importación de Librerias:**
"""

# ==============================================================
# 2 - Importación de Librerías
# ==============================================================
# Este bloque reúne todas las librerías necesarias para:

# ------------------------------
# Librerías del sistema / utilidad
# ------------------------------
import warnings
warnings.filterwarnings("ignore")  # para evitar mensajes molestos
import requests                    # extracción desde API

# ------------------------------
# Manipulación, análisis y cálculos
# ------------------------------
import numpy as np
import pandas as pd
from scipy import stats

# ------------------------------
# Visualizaciones (EDA)
# ------------------------------
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")  # estilo gráfico más limpio

# ------------------------------
# Preprocesamiento de datos
# ------------------------------
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# ------------------------------
# Modelos de Machine Learning
# ------------------------------
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# ------------------------------
# Validación cruzada
# ------------------------------
from sklearn.model_selection import cross_val_score

# ------------------------------
# Optimización de hiperparámetros
# ------------------------------
from sklearn.model_selection import GridSearchCV

# ------------------------------
# Métricas de evaluación de modelos
# ------------------------------
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ------------------------------
# Interpretabilidad de modelos
# ------------------------------
import shap

"""# **3 - Carga de Datos desde API AviationStack:**

Los datos fueron obtenidos mediante una API pública del sector aeronáutico, que proporciona información técnica y de registro de aeronaves a nivel mundial. Posteriormente, se almacenaron en formato CSV para su análisis local, garantizando reproducibilidad y facilidad de manipulación en Python.
"""

# ==============================================================
# 3 -  Obtener datos desde API AviationStack
# ==============================================================
API_KEY = "8583ba7525944d6d990eaa14e4c58b12"  # https://aviationstack.com
url = f"http://api.aviationstack.com/v1/airplanes?access_key={API_KEY}"

response = requests.get(url)
data = response.json()
df = pd.DataFrame(data['data'])
df.to_csv("aviationstack_airplanes.csv", index=False)
df.head()

"""# **4 - Limpieza de Datos:**

A partir del análisis del atributo df.info(), se observó que la mayoría de las columnas del dataset proveniente de la API aeronáutica se encontraban en formato object.

Por este motivo, se llevó a cabo un proceso de limpieza y transformación de datos con el objetivo de asegurar la correcta tipificación de las variables y la consistencia de los registros, permitiendo así un análisis estadístico y una visualización más precisa de los resultados.

Durante esta etapa se aplicaron las siguientes acciones:


1. **Eliminación de valores nulos:** Se eliminaron las filas que no contenían información sobre la línea de producción (production_line), por considerarse un campo esencial para el análisis comparativo entre modelos y fabricantes.

2. **Estandarización de nombres de columnas:** Se renombraron varias columnas para mejorar la legibilidad y coherencia con el dominio aeronáutico, utilizando una convención uniforme en español.

3. **Conversión de tipos de datos:** Se convirtieron las columnas con valores numéricos, como edad de la aeronave o cantidad de motores, a tipo float, mientras que las fechas se transformaron a tipo datetime para habilitar análisis temporales. Las variables categóricas y de texto se mantuvieron como str, aplicando una normalización básica para eliminar valores nulos, espacios y formatos inconsistentes.

4. **Detección y eliminación de duplicados:** Se eliminaron registros duplicados basados en los campos matrícula y número de serie, asegurando la unicidad de las aeronaves dentro del dataset.

5. **Verificación final del tipo de datos:** Posteriormente, se corroboró que las columnas relevantes respetaran los siguientes tipos de datos y descripciones:

| Campo                 | Tipo de dato | Descripción                                            |
| --------------------- | ------------ | ------------------------------------------------------ |
| id_aeronave           | str          | Identificador único del registro                       |
| tipo_iata             | str          | Código IATA del tipo de aeronave                       |
| id_modelo             | str          | Identificador interno del modelo                       |
| codigo_aerolinea_iata | str          | Código IATA de la aerolínea operadora                  |
| codigo_aerolinea_icao | str          | Código ICAO de la aerolínea                            |
| numero_serie          | str          | Número de serie o construcción                         |
| fecha_entrega         | datetime64   | Fecha de entrega de la aeronave                        |
| cantidad_motores      | float        | Número de motores                                      |
| tipo_motor            | str          | Tipo de propulsión (TURBOFAN, TURBOPROP, etc.)         |
| fecha_primer_vuelo    | datetime64   | Fecha de primer vuelo (si disponible)                  |
| codigo_hex            | str          | Código hexadecimal ICAO                                |
| modelo                | str          | Nombre del modelo (ej. 737-800, A320neo)               |
| propietario           | str          | Dueño o entidad operadora                              |
| estado_aeronave       | str          | Estado operativo (activo, almacenado, retirado)        |
| linea_produccion      | str          | Serie de producción (Boeing 737 NG, A320 Family, etc.) |
| edad_aeronave         | float        | Edad estimada de la aeronave                           |
| fecha_registro        | datetime64   | Fecha de registro del avión                            |
| fecha_rollout         | datetime64   | Fecha de salida de línea de producción                 |
"""

# ==============================================================
# 4 - Limpieza de Datos
# ==============================================================

def limpiar_datos_aeronauticos(df):
    """
    Realiza la limpieza completa y transformación de datos aeronáuticos

    Parámetros:
    -----------
    df : pandas.DataFrame
        DataFrame raw obtenido de la API AviationStack

    Retorna:
    --------
    pandas.DataFrame
        DataFrame limpio y transformado listo para análisis
    """

    # ==============================================================
    # PASO 1: DIAGNÓSTICO INICIAL - Evaluar estado original de los datos
    # ==============================================================
    print("=== INFORMACIÓN INICIAL DEL DATAFRAME ===")
    print("• Evaluando estructura y calidad inicial de los datos...")
    df.info()
    print(f"\n• Filas totales: {len(df)}")
    print(f"• Columnas disponibles: {len(df.columns)}")
    print(f"• Lista de columnas: {list(df.columns)}")

    # ==============================================================
    # PASO 2: ESTANDARIZACIÓN DE NOMBRES - Traducir y normalizar nombres de columnas
    # ==============================================================
    print("\n" + "="*50)
    print("RENOMBRANDO COLUMNAS")
    print("="*50)
    print("• Traduciendo nombres al español y estandarizando terminología aeronáutica...")

    # Diccionario de mapeo: inglés -> español
    mapeo_columnas = {
        # Identificadores únicos
        'id': 'id_aeronave',
        'airplane_id': 'id_modelo',

        # Códigos IATA/ICAO
        'iata_type': 'tipo_iata',
        'airline_iata_code': 'codigo_aerolinea_iata',
        'iata_code_long': 'codigo_iata_largo',
        'iata_code_short': 'codigo_iata_corto',
        'airline_icao_code': 'codigo_aerolinea_icao',
        'icao_code_hex': 'codigo_hex',

        # Información de fabricación
        'construction_number': 'numero_serie',
        'line_number': 'numero_linea',
        'model_code': 'codigo_modelo',
        'model_name': 'modelo',
        'production_line': 'linea_produccion',

        # Fechas importantes
        'delivery_date': 'fecha_entrega',
        'first_flight_date': 'fecha_primer_vuelo',
        'registration_date': 'fecha_registro',
        'rollout_date': 'fecha_rollout',

        # Especificaciones técnicas
        'engines_count': 'cantidad_motores',
        'engines_type': 'tipo_motor',
        'plane_age': 'edad_aeronave',
        'plane_class': 'clase_aeronave',
        'plane_series': 'serie_aeronave',

        # Información operacional
        'registration_number': 'matricula',
        'test_registration_number': 'matricula_prueba',
        'plane_owner': 'propietario',
        'plane_status': 'estado_aeronave'
    }

    df = df.rename(columns=mapeo_columnas)
    print(f"✓ Renombradas {len(mapeo_columnas)} columnas")

    # ==============================================================
    # PASO 3: FILTRADO DE DATOS - Eliminar registros incompletos o irrelevantes
    # ==============================================================
    print("\n" + "="*50)
    print("FILTRADO DE DATOS INCOMPLETOS")
    print("="*50)

    # Definir campos críticos para el análisis
    campos_criticos = ['linea_produccion', 'modelo', 'matricula']
    filas_antes = len(df)

    print(f"• Filtrando registros sin datos en campos críticos: {campos_criticos}")
    print(f"• Registros antes del filtrado: {filas_antes}")

    # Eliminar filas donde alguno de los campos críticos sea nulo
    df = df.dropna(subset=campos_criticos, how='any')

    filas_despues = len(df)
    filas_eliminadas = filas_antes - filas_despues
    print(f"✓ Registros después del filtrado: {filas_despues}")
    print(f"✓ Registros eliminados: {filas_eliminadas} ({filas_eliminadas/filas_antes*100:.1f}%)")

    # ==============================================================
    # PASO 4: TRANSFORMACIÓN DE TIPOS DE DATOS - Asegurar tipos correctos
    # ==============================================================
    print("\n" + "="*50)
    print("TRANSFORMACIÓN DE TIPOS DE DATOS")
    print("="*50)

    # --------------------------------------------------------------
    # 4.1 CONVERSIÓN DE VARIABLES NUMÉRICAS
    # --------------------------------------------------------------
    print("• Convirtiendo variables numéricas...")
    columnas_numericas = ['cantidad_motores', 'edad_aeronave', 'numero_linea']

    for columna in columnas_numericas:
        if columna in df.columns:
            valores_antes = df[columna].notna().sum()
            df[columna] = pd.to_numeric(df[columna], errors='coerce')
            valores_despues = df[columna].notna().sum()
            print(f"  ✓ {columna}: {valores_antes} → {valores_despues} valores válidos")

    # --------------------------------------------------------------
    # 4.2 CONVERSIÓN DE FECHAS
    # --------------------------------------------------------------
    print("• Convirtiendo variables de fecha...")
    columnas_fecha = ['fecha_entrega', 'fecha_primer_vuelo', 'fecha_registro', 'fecha_rollout']

    for columna in columnas_fecha:
        if columna in df.columns:
            valores_antes = df[columna].notna().sum()
            df[columna] = pd.to_datetime(df[columna], errors='coerce', utc=True)
            valores_despues = df[columna].notna().sum()
            print(f"  ✓ {columna}: {valores_antes} → {valores_despues} fechas válidas")

    # --------------------------------------------------------------
    # 4.3 NORMALIZACIÓN DE VARIABLES DE TEXTO
    # --------------------------------------------------------------
    print("• Normalizando variables de texto...")
    columnas_texto = [
        'id_aeronave', 'tipo_iata', 'id_modelo', 'codigo_aerolinea_iata',
        'codigo_iata_largo', 'codigo_iata_corto', 'codigo_aerolinea_icao',
        'numero_serie', 'codigo_hex', 'codigo_modelo', 'matricula',
        'matricula_prueba', 'clase_aeronave', 'modelo', 'propietario',
        'serie_aeronave', 'estado_aeronave', 'linea_produccion'
    ]

    for columna in columnas_texto:
        if columna in df.columns:
            # Convertir a string, eliminar espacios y reemplazar valores nulos
            df[columna] = (
                df[columna]
                .astype(str)
                .str.strip()
                .replace(['None', 'nan', 'NaT', 'NULL', ''], np.nan)
            )
    print(f"✓ Normalizadas {len(columnas_texto)} columnas de texto")

    # ==============================================================
    # PASO 5: NORMALIZACIÓN DE VALORES - Estandarizar formatos
    # ==============================================================
    print("\n" + "="*50)
    print("NORMALIZACIÓN DE VALORES")
    print("="*50)

    # Estado de aeronave en minúsculas para consistencia
    if 'estado_aeronave' in df.columns:
        df['estado_aeronave'] = df['estado_aeronave'].str.lower()
        print("✓ Estado de aeronave normalizado a minúsculas")

    # Tipo de motor en mayúsculas (estándar aeronáutico)
    if 'tipo_motor' in df.columns:
        df['tipo_motor'] = df['tipo_motor'].str.upper()
        print("✓ Tipo de motor normalizado a mayúsculas")

    # ==============================================================
    # PASO 6: ELIMINACIÓN DE DUPLICADOS - Garantizar unicidad de registros
    # ==============================================================
    print("\n" + "="*50)
    print("DETECCIÓN DE DUPLICADOS")
    print("="*50)

    # Buscar duplicados basados en identificadores únicos
    campos_unicos = ['matricula', 'numero_serie']
    duplicados = df.duplicated(subset=campos_unicos, keep='first').sum()

    print(f"• Duplicados detectados (basados en {campos_unicos}): {duplicados}")

    if duplicados > 0:
        df = df.drop_duplicates(subset=campos_unicos, keep='first')
        print(f"✓ {duplicados} registros duplicados eliminados")
    else:
        print("✓ No se encontraron registros duplicados")

    # ==============================================================
    # PASO 7: VALIDACIÓN Y LIMPIEZA DE VALORES EXTREMOS
    # ==============================================================
    print("\n" + "="*50)
    print("VALIDACIÓN DE VALORES EXTREMOS")
    print("="*50)

    # Validar y limpiar edad de aeronaves
    if 'edad_aeronave' in df.columns:
        filas_antes = len(df)

        # Asegurar tipo numérico
        df['edad_aeronave'] = pd.to_numeric(df['edad_aeronave'], errors='coerce')

        # Eliminar valores nulos en edad
        df = df[df['edad_aeronave'].notna()]
        filas_sin_nulos = len(df)

        # Filtrar valores extremos (aeronaves > 100 años consideradas erróneas)
        df = df[df['edad_aeronave'] < 100]
        filas_despues = len(df)

        print(f"• Validación de edad de aeronaves:")
        print(f"  - Registros antes: {filas_antes}")
        print(f"  - Sin valores nulos: {filas_sin_nulos}")
        print(f"  - Después de filtrar extremos (<100 años): {filas_despues}")
        print(f"  - Registros eliminados: {filas_antes - filas_despues}")

    # ==============================================================
    # PASO 8: VALIDACIÓN FINAL Y REPORTE
    # ==============================================================
    print("\n" + "="*50)
    print("VALIDACIÓN FINAL DEL DATAFRAME")
    print("="*50)

    print("=== ESTRUCTURA FINAL DEL DATAFRAME ===")
    df.info()

    print(f"\n=== RESUMEN DE LA LIMPIEZA ===")
    print(f"• Columnas finales: {len(df.columns)}")
    print(f"• Registros finales: {len(df)}")

    # Análisis de completitud por columna
    print(f"\n• COMPLETITUD POR COLUMNA (top 10 más completas):")
    completitud = (df.notna().sum() / len(df) * 100).sort_values(ascending=False)
    for col, perc in completitud.head(10).items():
        print(f"  {col:<25} {perc:6.1f}%")

    print("\n• MUESTRA DE DATOS LIMPIOS:")
    display(df.head(5))

    return df

# ==============================================================
# EJECUCIÓN DE LA LIMPIEZA
# ==============================================================
print("="*60)
print("🔧🔧🔧 INICIO DE PROCESO DE LIMPIEZA DE DATOS 🔧🔧🔧")
print("="*60)

# Ejecutar función de limpieza
df_limpio = limpiar_datos_aeronauticos(df)

print("\n" + "="*60)
print("✅✅✅ PROCESO DE LIMPIEZA COMPLETADO EXITOSAMENTE ✅✅✅")
print("="*60)

"""# **5 - Análisis Exploratorio de Datos (EDA)**

En esta sección se desarrolla un análisis descriptivo del dataset limpio, mediante herramientas estadísticas y visualizaciones.  

El objetivo es identificar patrones, tendencias y relaciones entre las variables que describen las aeronaves: antigüedad, línea de producción, tipo de motor y estado operativo.

## **5.1 - RESUMEN ESTADÍSTICO Y CALIDAD DE DATOS**

Este bloque de código realiza un análisis de la calidad y estructura del dataset aeronáutico. La función genera un reporte estructurado que evalúa:

1.   Información general (91 registros con 26 variables).

2.   Completitud de campos críticos (todos al 100%).

3.   Estadísticas numéricas (destacando una edad promedio de 19.9 años en aeronaves).

4.   Distribución de categorías.

Los resultados revelan un dataset con calidad aceptable (80.3% de completitud global) y excelente integridad en campos críticos (100%), donde predominan aeronaves con motores JET (61 vs 30 TURBOPROP) y configuraciones bimotor.

Por otro lado, la columna "codigo_aerolinea_icao" muestra problemas de completitud (0 registros válidos).
"""

# ==============================================================
# BLOQUE 1: RESUMEN ESTADÍSTICO Y CALIDAD DE DATOS
# ==============================================================

def analisis_calidad_datos_simple(df):
    """
    Función para explorar la calidad de datos de forma sencilla:
    - Ver cantidad de registros y columnas
    - Ver completitud de columnas importantes
    - Resumen de estadísticas numéricas
    - Resumen de variables categóricas
    """

    print("="*60)
    print("BLOQUE 1: RESUMEN DE DATOS")
    print("="*60)

    # 1. Información general
    print(f"\n1. INFORMACIÓN GENERAL:\n")
    print(f"Total de registros: {len(df):,}")
    print(f"Total de columnas: {len(df.columns)}\n")

    # 2️. Completitud columnas críticas
    print("-"*60)
    print("\n2. COMPLETITUD DE COLUMNAS CRÍTICAS:\n")
    columnas_criticas = ['matricula', 'linea_produccion', 'edad_aeronave',
                         'tipo_motor', 'estado_aeronave', 'cantidad_motores']
    print("Completitud columnas críticas:")
    for col in columnas_criticas:
        if col in df.columns:
            completitud = df[col].notna().mean() * 100
            print(f"  {col:<20}: {completitud:.1f}% completos | {df[col].nunique()} valores únicos")
        else:
            print(f"  {col:<20}: NO DISPONIBLE")

    # 3️. Estadísticas de columnas numéricas
    print("-"*60)
    print("\n3. ESTADÍSTICAS DE COLUMNAS NUMÉRICAS:\n")
    num_cols = df.select_dtypes(include='number').columns
    if len(num_cols) > 0:
        print("\nEstadísticas de columnas numéricas:")
        print(df[num_cols].describe().round(2))
    else:
        print("\nNo hay columnas numéricas")

    # 4️. Resumen de columnas categóricas
    print("-"*60)
    print("\n4. RESUMEN DE COLUMNAS CATEGÓRICAS:")
    cat_cols = ['linea_produccion', 'tipo_motor', 'estado_aeronave']
    for col in cat_cols:
        if col in df.columns:
            print(f"\nDistribución de {col}:")
            print(df[col].value_counts().head(5))  # muestra las 5 más comunes
            if df[col].nunique() > 5:
                print(f"... y {df[col].nunique() - 5} más categorías")

    # 5️. Calidad general
    print("")
    print("-"*60)
    print("\n5. CALIDAD GENERAL DEL DATASET:\n")
    completitud_global = df.notna().mean().mean() * 100
    registros_completos = df[columnas_criticas].notna().all(axis=1).mean() * 100
    print(f"Completitud global: {completitud_global:.1f}%")
    print(f"Registros completamente limpios (columnas críticas): {registros_completos:.1f}%")
    print("")
    print("-"*60)
    return {
        'completitud_global': completitud_global,
        'registros_completos': registros_completos,
        'columnas_numericas': list(num_cols),
        'estructura_dataset': df.shape
    }

# EJECUTAR BLOQUE 1
resultados_bloque1 = analisis_calidad_datos_simple(df_limpio)

"""## **5.2 - DISTRIBUCIÓN DE EDAD DE AERONAVES**

Este bloque de código realiza un análisis descriptivo de la distribución de edades de las aeronaves mediante visualizaciones estadísticas. La función "graficos_edad_aeronaves" genera dos gráficos complementarios:

* Un histograma con curva de densidad que muestra la frecuencia de edades.

* Un diagrama de caja que revela la dispersión y posibles valores atípicos.

Los resultados muestran una flota con edad promedio de 19.9 años y mediana de 19.0 años, indicando una distribución relativamente simétrica. La moda en 17.0 años sugiere una concentración de aeronaves más jóvenes, mientras que la desviación estándar de 7.2 años refleja una variabilidad moderada en las edades.
"""

# ==============================================================
# BLOQUE 2: DISTRIBUCIÓN DE EDAD DE AERONAVES
# ==============================================================

# 1. Estilo global
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_theme(style="whitegrid", palette="Set2")

def graficos_edad_aeronaves(df):
    """
    Analiza cómo se distribuye la edad de las aeronaves.
    Muestra histograma con líneas de media, mediana y moda, y boxplot.
    """
    print("="*60)
    print("BLOQUE 2: DISTRIBUCIÓN DE EDAD DE AERONAVES")
    print("="*60)
    print("")

    if 'edad_aeronave' not in df.columns:
        print("No existe la columna 'edad_aeronave' en el dataset.")
        return

    # 2. Preprocesamiento
    edad = df['edad_aeronave'].dropna()

    # 3. Estadísticas básicas
    media = edad.mean()
    mediana = edad.median()
    moda = edad.mode().iloc[0] if not edad.mode().empty else np.nan
    desvio = edad.std()
    n = len(edad)

    # 4. Crear figura con dos gráficos
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # ==========================================================
    # Gráfico 1: Histograma con líneas estadísticas
    # ==========================================================
    sns.histplot(
          edad,
          bins=31,
          kde=True,
          color="lightgreen",      # color del histograma
          edgecolor="black",
          ax=axes[0]
          )

    # 5. Cambiar color y grosor de la curva KDE después de crearla
    for line in axes[0].lines:
        line.set_color("#338833")   # color de la curva de densidad
        line.set_linewidth(2)        # grosor

    # 6. Líneas de referencia
    axes[0].axvline(media, color='red', linestyle='--', linewidth=1.5, label=f"Media: {media:.1f}")
    axes[0].axvline(mediana, color='green', linestyle='--', linewidth=1.5, label=f"Mediana: {mediana:.1f}")
    axes[0].axvline(moda, color='orange', linestyle='--', linewidth=1.5, label=f"Moda: {moda:.1f}")

    axes[0].set_title("Distribución de Edad de Aeronaves", fontsize=12, fontweight="bold")
    axes[0].set_xlabel("Edad (años)")
    axes[0].set_ylabel("Densidad")
    axes[0].legend()

    # ==========================================================
    # Gráfico 2: Boxplot
    # ==========================================================
    sns.boxplot(x=edad, color="lightgreen", width=0.3, ax=axes[1])
    axes[1].set_title("Diagrama de Caja - Edad de Aeronaves", fontsize=12, fontweight="bold")
    axes[1].set_xlabel("Edad (años)")

    plt.tight_layout()
    plt.show()

    # ==========================================================
    # Estadísticas básicas
    # ==========================================================
    print("")
    print("-"*60)
    print("")
    print("ESTADÍSTICAS BÁSICAS:")
    print("")
    print(f"Promedio: {media:.1f} años")
    print(f"Mediana: {mediana:.1f} años")
    print(f"Moda: {moda:.1f} años")
    print(f"Desviación estándar: {desvio:.1f} años")
    print(f"Valores válidos: {n} registros\n")
    print("-"*60)

# EJECUTAR BLOQUE 2
graficos_edad_aeronaves(df_limpio)

"""## **5.3 - DISTRIBUCIÓN DE CANTIDAD DE MOTORES**

Este bloque de código analiza la distribución de configuraciones de motores en la flota aeronáutica mediante visualizaciones comparativas. La función "graficos_cantidad_motores" genera dos representaciones gráficas:

* Un gráfico de barras que muestra la frecuencia absoluta de cada configuración.

* Un gráfico circular que presenta la distribución porcentual.

Los resultados revelan una predominancia de aeronaves bimotor (89 unidades, 97.8%), mientras que las configuraciones cuatrimotor representan solo 2 aeronaves (2.2%). Esta distribución refleja la tendencia actual en la industria hacia configuraciones más eficientes en combustible y menores costos de mantenimiento, siendo la configuración bimotor el estándar predominante en la flota analizada.
"""

# ==============================================================
# BLOQUE 3: DISTRIBUCIÓN DE CANTIDAD DE MOTORES
# ==============================================================

# 1. Ignorar solo los FutureWarnings de Seaborn
warnings.simplefilter(action='ignore', category=FutureWarning)

# 2. Estilo global
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_theme(style="whitegrid")

def graficos_cantidad_motores(df):
    """
    Analiza cómo se distribuye la cantidad de motores en las aeronaves.
    Muestra un gráfico de barras y un gráfico circular con estilo uniforme.
    """
    print("=" * 60)
    print("BLOQUE 3: DISTRIBUCIÓN DE CANTIDAD DE MOTORES")
    print("=" * 60)
    print("" * 60)

    if 'cantidad_motores' not in df.columns:
        print("No existe la columna 'cantidad_motores' en el dataset.")
        return

    # Preprocesamiento
    motores = df['cantidad_motores'].dropna()
    conteo = motores.value_counts().sort_index()

    # Figura con 2 gráficos
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    colores = sns.color_palette("Set2", n_colors=len(conteo))

    # ==========================================================
    # Gráfico 1: Barras
    # ==========================================================
    sns.barplot(
        x=conteo.index,
        y=conteo.values,
        palette=colores,  # usar misma paleta
        ax=axes[0],
        edgecolor="black"
    )

    axes[0].set_title("Distribución de Cantidad de Motores", fontsize=12, fontweight="bold")
    axes[0].set_xlabel("Número de motores")
    axes[0].set_ylabel("Cantidad de aeronaves")

    # Etiquetas sobre las barras
    for i, val in enumerate(conteo.values):
        axes[0].text(i, val + 0.5, f"{val}", ha='center', fontsize=10, fontweight='bold')

    # ==========================================================
    # Gráfico 2: Circular
    # ==========================================================
    wedges, texts, autotexts = axes[1].pie(
        conteo.values,
        labels=conteo.index,
        autopct='%1.1f%%',
        startangle=90,
        colors=colores,  # misma paleta que el barplot
        textprops={'fontsize': 10}
    )
    axes[1].set_title("Distribución Porcentual de Motores", fontsize=12, fontweight="bold")
    axes[1].axis('equal')  # Circular perfecta

    plt.tight_layout()
    plt.show()

    # ==========================================================
    # Estadísticas básicas
    # ==========================================================
    print("\n" + "-"*60)
    print("")
    print("ESTADÍSTICAS BÁSICAS:\n")
    print("Distribución de motores:")
    for mot, cantidad in conteo.items():
        porcentaje = (cantidad / len(df)) * 100
        print(f"  - {mot} motores: {cantidad} aeronaves ({porcentaje:.1f}%)")
    print(f"Configuración más común: {conteo.idxmax()} motores")
    print(""*60)
    print("-"*60)

# EJECUTAR BLOQUE 3
graficos_cantidad_motores(df_limpio)

"""## **5.4 - DISTRIBUCIÓN DE LÍNEAS DE PRODUCCIÓN**

Este bloque de código analiza la diversidad y concentración de las líneas de producción en la flota aeronáutica. La función "analisis_lineas_produccion_bloqueA" utiliza dos visualizaciones complementarias:

* Un gráfico de barras horizontales que muestra las 10 líneas más representadas por cantidad de aeronaves.

* Un gráfico circular que presenta su distribución porcentual.

Los resultados revelan una flota diversificada con 17 líneas de producción distintas, donde predominan los modelos "Bombardier CRJ-100/2" y "ATR 42/72" (14 aeronaves cada uno), seguidos por "Boeing 737 Classic" (13 aeronaves). La alta concentración en las 10 principales líneas (90.1% del total) indica una estrategia de estandarización en la flota, mientras que la presencia de 7 líneas adicionales con menor representación sugiere cierta diversificación operativa.
"""

# ==============================================================
# BLOQUE 4: LÍNEAS DE PRODUCCIÓN
# ==============================================================

def analisis_lineas_produccion_bloqueA(df, top_n=10):
    print("="*60)
    print("BLOQUE 4: LÍNEAS DE PRODUCCIÓN")
    print("="*60)
    print(""*60)

    if 'linea_produccion' not in df.columns:
        print("Columna 'linea_produccion' no disponible")
        return {}

    # Distribución y top N
    distribucion_lineas = df['linea_produccion'].value_counts()
    top_lineas = distribucion_lineas.head(top_n)

    # Configuración de figura
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # ==========================================================
    # Gráfico 1: Barras horizontales
    # ==========================================================
    bars = axes[0].barh(range(len(top_lineas)), top_lineas.values,
                        color=plt.cm.Greens(np.linspace(0.5, 0.8, len(top_lineas))))
    axes[0].set_yticks(range(len(top_lineas)))
    axes[0].set_yticklabels(top_lineas.index)
    axes[0].set_title('Top Líneas de Producción\n(Cantidad de Aeronaves)',
                      fontsize=14, fontweight='bold')
    axes[0].set_xlabel('Número de Aeronaves')

    # Etiquetas en las barras
    for i, (bar, valor) in enumerate(zip(bars, top_lineas.values)):
        axes[0].text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                     f'{valor}', ha='left', va='center', fontweight='bold')

    # ==========================================================
    # Gráfico 2: Pie chart
    # ==========================================================
    axes[1].pie(top_lineas.values, labels=top_lineas.index,
                autopct=lambda p: f'{p:.1f}%', startangle=90,
                colors=plt.cm.Set3(np.linspace(0, 1, len(top_lineas))))
    axes[1].set_title('Distribución Porcentual del Top Líneas',
                      fontsize=14, fontweight='bold')

    plt.tight_layout()
    plt.show()

    # ==========================================================
    # Estadísticas básicas
    # ==========================================================
    print("")
    print("-"*60)
    print("")
    print("ESTADÍSTICAS BÁSICAS:")
    print("")
    print(f"Total de líneas distintas: {len(distribucion_lineas)}")
    print(f"Línea más representada: {top_lineas.index[0]} ({top_lineas.iloc[0]} aeronaves)")
    print(f"Porcentaje del top {top_n}: {top_lineas.sum()/len(df)*100:.1f}%")
    print(""*60)
    print("-"*60)

# EJECUTAR BLOQUE 4
analisis_lineas_produccion_bloqueA(df_limpio)

"""## **5.5 - DISTRIBUCIÓN DE FABRICANTES PRINCIPALES**

Este bloque de código analiza la estructura del mercado de fabricantes aeronáuticos en la flota. La función "analisis_fabricantes_bloqueB" extrae el fabricante principal de cada aeronave a partir de la primera palabra de la línea de producción y genera dos visualizaciones:

* Un gráfico de barras que muestra los 5 fabricantes más representados.

* Un panel de métricas que resume la diversidad del mercado.

Los resultados revelan un panorama competitivo con 11 fabricantes distintos operando en 17 líneas de producción diferentes. Boeing emerge como fabricante líder con 16 aeronaves, seguido por otros importantes actores. La concentración moderada en los tres principales fabricantes (49.5% de la flota) indica un mercado diversificado sin dominio absoluto de un solo jugador, reflejando un ecosistema  balanceado entre fabricantes establecidos y especializados.
"""

# ==============================================================
# BLOQUE 5: FABRICANTES PRINCIPALES
# ==============================================================

def analisis_fabricantes_bloqueB(df, top_n=5):
    print("="*60)
    print("BLOQUE 5: FABRICANTES PRINCIPALES")
    print("="*60)
    print(""*60)

    if 'linea_produccion' not in df.columns:
        print("Columna 'linea_produccion' no disponible")
        return {}

    # Extraer fabricante (primer palabra de linea_produccion)
    df['fabricante'] = df['linea_produccion'].str.split().str[0]
    distribucion_fabricantes = df['fabricante'].value_counts()
    top_fabricantes = distribucion_fabricantes.head(top_n)

    # Crear figura con 2 gráficos
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # ==========================================================
    # Gráfico 1: Barras de fabricantes
    # ==========================================================
    colores = plt.cm.Greens(np.linspace(0.4, 0.8, len(top_fabricantes)))
    axes[0].bar(range(len(top_fabricantes)), top_fabricantes.values,
                color=colores, edgecolor='black')
    axes[0].set_xticks(range(len(top_fabricantes)))
    axes[0].set_xticklabels(top_fabricantes.index, rotation=45)
    axes[0].set_title(f'Top {top_n} Fabricantes por Número de Aeronaves',
                      fontsize=14, fontweight='bold')
    axes[0].set_ylabel('Cantidad de Aeronaves')

    # Etiquetas en las barras
    for i, valor in enumerate(top_fabricantes.values):
        axes[0].text(i, valor + 0.5, f'{valor}', ha='center', va='bottom', fontweight='bold')

    # ==========================================================
    # Gráfico 2: Métricas de diversidad mejoradas
    # ==========================================================
    total_fabricantes = len(distribucion_fabricantes)
    total_lineas = len(df['linea_produccion'].value_counts())
    cuota_top3 = distribucion_fabricantes.head(3).sum() / len(df) * 100
    fabricante_lider = distribucion_fabricantes.index[0]
    cantidad_lider = distribucion_fabricantes.iloc[0]

    texto_metricas = (
        f"Total Fabricantes: {total_fabricantes}\n"
        f"Total Líneas: {total_lineas}\n"
        f"Top 3 Fabricantes: {cuota_top3:.1f}% de la flota\n"
        f"Fabricante líder: {fabricante_lider} ({cantidad_lider} aeronaves)"
    )

    axes[1].text(0.5, 0.5, texto_metricas,
                 ha='center', va='center', transform=axes[1].transAxes,
                 fontsize=14, bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    axes[1].set_title('Métricas de Diversidad del Mercado',
                      fontsize=14, fontweight='bold')
    axes[1].axis('off')

    plt.tight_layout()
    plt.show()

    # ==========================================================
    # Estadísticas básicas
    # ==========================================================
    print("\n" + "-"*60)
    print("")
    print("ESTADÍSTICAS BÁSICAS:\n")
    print(f"Total de fabricantes distintos: {total_fabricantes}")
    print(f"Total de líneas de producción: {total_lineas}")
    print(f"Porcentaje del top 3 fabricantes: {cuota_top3:.1f}%")
    print(f"Fabricante líder: {fabricante_lider} ({cantidad_lider} aeronaves)")
    print("")
    print("-"*60 + "\n")


# EJECUTAR BLOQUE 5
analisis_fabricantes_bloqueB(df_limpio)

"""## **5.6 - Conclusiones e Insights del EDA**

---

El análisis exploratorio revela una flota aeronáutica compuesta por 91 aeronaves con una estructura operativa bien definida. La calidad de datos es aceptable (80.3% de completitud global) con excelente integridad en campos críticos (100%).

---

**Composición y Antigüedad:**

La flota presenta una edad promedio de 19.9 años, con distribución relativamente simétrica (mediana: 19.0 años) y concentración en aeronaves más jóvenes (moda: 17.0 años). Se confirma que las aeronaves de la línea Boeing 737 Classic presentan la mayor antigüedad promedio, lo que sugiere necesidad de renovación prioritaria.

---

**Configuraciones Técnicas:**

Existe una predominancia de configuraciones bimotor (97.8%), alineada con tendencias modernas de eficiencia. Los motores de tipo JET (TURBOFAN) dominan la flota (61 unidades) frente a TURBOPROP (30 unidades), reflejando la transición hacia tecnologías más eficientes.

---

**Diversidad de Fabricantes:**

El mercado muestra 11 fabricantes compitiendo en 17 líneas de producción distintas. Boeing lidera con 16 aeronaves, seguido por Bombardier y ATR (14 cada uno). La concentración moderada (49.5% en top 3 fabricantes) indica un ecosistema competitivo balanceado.

---

**Estado Operativo:**

La flota mantiene alto porcentaje de aeronaves activas (73 vs 18 inactivas), con concentración en líneas de producción modernas que refleja la tendencia hacia eficiencia y sostenibilidad.

---

**Insights Estratégicos:**

* Renovación Prioritaria: La antigüedad de Boeing 737 Classic sugiere necesidad de renovación programada

* Estandarización Exitosa: La concentración en configuraciones bimotor y motores JET optimiza costos de mantenimiento

* Diversificación Controlada: Balance entre estandarización (top 10 líneas: 90.1%) y flexibilidad operativa

---

# **6 - Ingeniería de Atributos**

En esta etapa se toman las variables originales del dataset y se transforman para que puedan ser utilizadas por los modelos de Machine Learning.

La ingeniería de atributos aplicada incluye:

- Selección de variables relevantes relacionadas con la edad, configuración y línea de producción de la aeronave.

- Codificación de variables categóricas mediante One-Hot Encoding para poder utilizarlas en modelos matemáticos.

- Normalización / estandarización de variables numéricas para asegurar que todas las características operen en la misma escala.

- Creación de atributos derivados específicos del dominio aeronáutico, incluyendo la clasificación de la vida útil remanente (RUL) en categorías como long life, mid life y near retirement.

- Construcción final de la matriz de entrenamiento (X) y la variable objetivo (y) preparada para el modelo predictivo.

El objetivo principal de este proceso es estructurar los datos de manera que describan adecuadamente el estado y envejecimiento de cada aeronave, permitiendo entrenar un modelo capaz de predecir su vida útil restante de forma confiable.
"""

# ============================
# 6 - Ingeniería de Atributos (RUL - vida útil restante)
# ============================

df_ml = df_limpio.copy()

# -----------------------------
# 0) Generación de la etiqueta RUL
# -----------------------------
def clasificar_rul(row):
    try:
        age = float(row.get("edad_aeronave", np.nan))
    except:
        age = np.nan

    line = row.get("linea_produccion", "")

    modelos_antiguos = [
        "Boeing 737 Classic", "MD-80", "MD-90",
        "Fokker", "Dornier", "Fairchild Dornier",
        "Antonov", "Boeing 747", "Bombardier CRJ-100/2"
    ]

    if pd.isna(age):
        return np.nan

    if any(m.lower() in str(line).lower() for m in modelos_antiguos):
        return "near_retirement"

    if age > 27:
        return "near_retirement"
    elif age > 15:
        return "mid_life"
    else:
        return "long_life"

df_ml["rul_category"] = df_ml.apply(clasificar_rul, axis=1)

# -----------------------------
# 1) Selección de características
# -----------------------------
features = ['edad_aeronave', 'cantidad_motores', 'tipo_motor', 'linea_produccion']
target = 'rul_category'

df_ml = df_ml[features + [target]].dropna(subset=[target, 'edad_aeronave'])

# -----------------------------
# 2) One-Hot Encoding
# -----------------------------
df_encoded = pd.get_dummies(
    df_ml,
    columns=['tipo_motor', 'linea_produccion'],
    drop_first=True
)

# -----------------------------
# 3) X / y como DataFrames
# -----------------------------
X_df = df_encoded.drop(columns=[target]).copy()
y = df_encoded[target].astype("category")
X_columns = X_df.columns.tolist()

# -----------------------------
# 4) División antes del escalado (MUY IMPORTANTE)
# -----------------------------
X_train_df, X_test_df, y_train, y_test = train_test_split(
    X_df,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# -----------------------------
# 5) Estandarización solo después del split
# -----------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_df)
X_test = scaler.transform(X_test_df)

# -----------------------------
# Información para control
# -----------------------------
print("Shapes sin escalar:", X_train_df.shape, X_test_df.shape)
print("Shapes escalados:", X_train.shape, X_test.shape)

print("Distribución target (train):")
print(y_train.value_counts(normalize=True))

print("Distribución target (test):")
print(y_test.value_counts(normalize=True))

"""# **7 - Entrenamiento y Validación Cruzada**

En esta etapa se entrenan y comparan distintos algoritmos de Machine Learning ampliamente utilizados para problemas de clasificación.

El objetivo es establecer una línea de base del desempeño general antes de realizar ajustes más avanzados como la optimización de hiperparámetros.

Se incluyen los siguientes modelos:

- Regresión Logística.

- Random Forest Classifier.

- Gradient Boosting Classifier.

- Support Vector Machine (SVM).

- K-Nearest Neighbors (KNN).

Todos los modelos se evaluaron utilizando validación cruzada estratificada (k=5). Esta validación cruzada estratificada divide el dataset en cinco partes manteniendo la misma proporción de clases en cada una. El modelo se entrena con cuatro partes y se evalúa en la parte restante, repitiendo este proceso cinco veces. Luego se promedian los resultados. Esto permite obtener una estimación más confiable del desempeño real del modelo, especialmente cuando las clases están desbalanceadas.

Esta metodología permite estimar la capacidad de generalización de cada modelo y seleccionar los que luego serán optimizados.
"""

# ======================================
# 7 - Entrenamiento + Validación Cruzada (Multiclase RUL)
# ======================================

# 1. Definimos los modelos a evaluar
# Se agregan parámetros para mejorar el desempeño en problemas multiclase y desbalanceados.
modelos = {
    "Regresión Logística": LogisticRegression(
        max_iter=2000,
        multi_class="multinomial",
        class_weight="balanced"
    ),
    "Random Forest": RandomForestClassifier(
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(),
    "SVM (SVC)": SVC(
        kernel="linear",
        class_weight="balanced"
    ),
    "KNN": KNeighborsClassifier()
}

# Diccionario para guardar los resultados de accuracy promedio
resultados = {}

# 2. Validación cruzada k=5
# Mantiene la proporción de clases en cada fold (estratificada).
for nombre, modelo in modelos.items():
    scores = cross_val_score(
        modelo,
        X_train,
        y_train,
        cv=5,                # 5 particiones
        scoring='accuracy'   # métrica base
    )

    # Guardamos el promedio de accuracy del modelo
    resultados[nombre] = scores.mean()

    # Mostramos el desempeño promedio
    print(f"{nombre}: Accuracy promedio = {scores.mean():.4f}")

# 3. Resultados como tabla
pd.DataFrame.from_dict(resultados, orient='index', columns=['Accuracy promedio'])

"""# **8 - Entrenamiento final de modelos**

Luego de la evaluación base mediante validación cruzada, se seleccionan los modelos candidatos para ser entrenados completamente antes de realizar la optimización de hiperparámetros.

En esta etapa, cada modelo se ajusta utilizando el conjunto completo de entrenamiento (X_train, y_train), lo que permite obtener una primera referencia de su desempeño global y establecer una línea de base coherente para comparar sus resultados en condiciones idénticas.

Dado que el problema consiste en predecir la vida útil remanente (RUL) en un escenario multiclase y con clases moderadamente desbalanceadas, los modelos se inicializan utilizando los mismos parámetros que fueron evaluados durante la validación cruzada. Esto asegura consistencia metodológica y evita cambios en el comportamiento estadístico de los clasificadores. En particular, modelos como Regresión Logística y SVM requieren activar la opción multiclase y el balanceo automático de clases para un rendimiento adecuado.

Los modelos entrenados en esta etapa son:

- Regresión Logística (multiclase con balanceo).

- Random Forest.

- Gradient Boosting.

- SVM (con probability=True para análisis interpretables como SHAP).

- KNN (incluido solo como referencia comparativa).

Aunque en etapas posteriores solo se optimizarán los modelos con mejor desempeño (generalmente Gradient Boosting, Random Forest y SVM), aquí todos son ajustados para obtener una primera referencia clara de su comportamiento sobre el dataset completo.

Este entrenamiento inicial constituye la base para la fase de optimización y evaluación final, asegurando que cada algoritmo sea comparado en igualdad de condiciones y con los mismos datos disponibles.
"""

# ========================================================
# 8 - Entrenamiento final de modelos (Multiclase RUL)
# ========================================================

# 1. Definimos los modelos a entrenar con los mismos parámetros
#    utilizados en la validación cruzada. Esto garantiza consistencia
#    y prepara los modelos para la etapa de optimización posterior.
modelos_final = {
    "Regresión Logística": LogisticRegression(
        max_iter=2000,
        multi_class="multinomial",
        class_weight="balanced"
    ),

    "Random Forest": RandomForestClassifier(
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingClassifier(),

    "SVM": SVC(
        kernel="linear",
        class_weight="balanced",
        probability=True  # necesario para SHAP más adelante
    ),

    # KNN se mantiene solo para referencia; no será optimizado después.
    "KNN": KNeighborsClassifier()
}

# Diccionario donde guardaremos los modelos entrenados
modelos_entrenados = {}

# 2. Entrenamos cada modelo utilizando el dataset completo de entrenamiento
for nombre, modelo in modelos_final.items():
    modelo.fit(X_train, y_train)  # ajuste completo del modelo
    modelos_entrenados[nombre] = modelo
    print(f"Modelo entrenado: {nombre}")

"""# **9 - Optimización de Hiperparámetros**

Después del entrenamiento inicial, se seleccionan los modelos con mejor desempeño para optimizar sus hiperparámetros.

Los modelos de machine learning tienen hiperparámetros que controlan su comportamiento (profundidad de los árboles, tasa de aprendizaje, regularización, etc.). Ajustarlos correctamente permite mejorar la capacidad de generalización, evitar overfitting o underfitting, y obtener modelos más robustos y precisos.

Los modelos típicamente más prometedores en clasificación tabular suelen ser:

- Random Forest.

- Gradient Boosting.
  
- SVM.  

Por su naturaleza, son modelos que capturan relaciones complejas no lineales y suelen beneficiarse del proceso de grid search.

Se utiliza GridSearchCV (o en algunos casos RandomizedSearchCV) para explorar diferentes combinaciones de hiperparámetros. La búsqueda se realiza mediante:

- Validación cruzada k=5, lo cual garantiza mayor estabilidad en la estimación del rendimiento.

- Métrica principal ajustada según el problema (por ejemplo, accuracy, recall, F1-score).

Este procedimiento analiza múltiples configuraciones posibles, entrena el modelo con cada una y selecciona aquella que maximiza el rendimiento promedio en la validación cruzada.
"""

# ============================
# 9 - Optimización de modelos
# ============================

# 1. Definimos los rangos de hiperparámetros a evaluar para cada modelo
param_rf = {
    "n_estimators": [100, 200, 400],
    "max_depth": [5, 10, 20, None],
    "min_samples_split": [2, 5, 10]
}

param_gb = {
    "n_estimators": [100, 200],
    "learning_rate": [0.05, 0.1, 0.2],
    "max_depth": [2, 3, 4]
}

param_svm = {
    "C": [0.1, 1, 10],
    "kernel": ["rbf", "linear"],
    "gamma": ["scale", "auto"]
}

# 2. Asociamos cada modelo con su conjunto de hiperparámetros para optimizar
grids = {
    "Random Forest": (RandomForestClassifier(random_state=42), param_rf),
    "Gradient Boosting": (GradientBoostingClassifier(), param_gb),
    "SVM": (SVC(probability=True), param_svm)
}

mejores_modelos = {}

# 3. Ejecutamos GridSearchCV para encontrar la mejor combinación de hiperparámetros
for nombre, (modelo, params) in grids.items():
    print(f"\nOptimizando: {nombre}")
    grid = GridSearchCV(modelo, params, cv=5, scoring="accuracy", n_jobs=-1)
    grid.fit(X_train, y_train)
    mejores_modelos[nombre] = grid.best_estimator_
    print("Mejores parámetros:", grid.best_params_)
    print("Mejor accuracy en CV:", grid.best_score_)

"""Tras ejecutar GridSearchCV con validación cruzada estratificada (k=5), se identificaron las mejores combinaciones de hiperparámetros para cada uno de los modelos seleccionados. Los resultados finales fueron los siguientes:

- Random Forest alcanzó su mejor desempeño con
400 árboles, profundidad máxima = 10, y min_samples_split = 2,
logrando un accuracy promedio de 0.930 en la validación cruzada.

- Gradient Boosting obtuvo la mejor configuración con
learning rate = 0.05, 100 árboles, y profundidad máxima = 2,
alcanzando el mejor accuracy general del experimento: 0.946.

- SVM mostró su mejor rendimiento utilizando
kernel lineal, C = 1, y gamma = 'scale',
con un accuracy promedio de 0.916.

En resumen, Gradient Boosting se posiciona como el modelo con mayor capacidad predictiva.

# **10 - Evaluación y Selección del Mejor Modelo**

## **10.1 y 10.2- Evaluación Final de cada Modelo**

Los modelos optimizados se evalúan sobre el conjunto de test (20%) para medir su capacidad real de generalización.

Para esta evaluación se emplean métricas estándar en problemas de clasificación:

- Accuracy: proporción total de aciertos.  

- Matriz de confusión: permite visualizar errores por clase.  

- Reporte de clasificación: incluye precision, recall y f1-score para un análisis más detallado.

Finalmente, se selecciona el modelo con mejor desempeño global.
"""

# =====================================================
# 10.1 - Evaluación final con visualizaciones mejoradas
# =====================================================

# 1. Diccionario donde se guardará el accuracy final de cada modelo optimizado
scores_finales = {}

for nombre, modelo in mejores_modelos.items():

    # --- PREDICCIONES ---
    pred = modelo.predict(X_test)
    acc = accuracy_score(y_test, pred)
    scores_finales[nombre] = acc

    print(f"\n===== {nombre} =====")
    print(f"Accuracy final: {acc:.4f}")

    # --- REPORTE COMPLETO ---
    print("\nReporte de clasificación:")
    print(classification_report(y_test, pred))

    # --- MATRIZ DE CONFUSIÓN ---
    cm = confusion_matrix(y_test, pred)
    cm_norm = confusion_matrix(y_test, pred, normalize='true')

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Matriz clásica
    sns.heatmap(
        cm, annot=True, cmap="Blues", fmt="d", ax=axes[0],
        cbar=False, linewidths=.5, linecolor='gray'
    )
    axes[0].set_title(f"{nombre} - Matriz de Confusión")
    axes[0].set_xlabel("Predicción")
    axes[0].set_ylabel("Real")

    # Matriz normalizada
    sns.heatmap(
        cm_norm, annot=True, cmap="Greens", fmt=".2f", ax=axes[1],
        cbar=False, linewidths=.5, linecolor='gray'
    )
    axes[1].set_title(f"{nombre} - Matriz Normalizada")
    axes[1].set_xlabel("Predicción")
    axes[1].set_ylabel("Real")

    plt.tight_layout()
    plt.show()

# =====================================================
# 10.2 - Comparación visual del desempeño final
# =====================================================

plt.figure(figsize=(8, 5))
sns.barplot(
    x=list(scores_finales.keys()),
    y=list(scores_finales.values()),
    palette="viridis"
)

plt.title("Comparación de accuracy final por modelo", fontsize=14)
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.show()

# Selección del mejor modelo
mejor_modelo_nombre = max(scores_finales, key=scores_finales.get)
mejor_modelo = mejores_modelos[mejor_modelo_nombre]

print(f"\n\n🔥 Mejor modelo seleccionado: **{mejor_modelo_nombre}**")

"""Los modelos optimizados fueron evaluados sobre el conjunto de test (20%).
Tanto Random Forest como Gradient Boosting alcanzaron un accuracy del 100%, clasificando correctamente todas las aeronaves según su categoría de vida útil (long_life, mid_life, near_retirement).

Este resultado, si bien elevado, es coherente con la estructura del dataset:

- El conjunto de datos es pequeño y está altamente ordenado.

- La variable edad de la aeronave resulta extremadamente informativa para determinar su categoría.

- Los modelos basados en árboles capturan patrones no lineales simples de manera muy eficiente.

Por otro lado, el modelo SVM, menos flexible, obtuvo un accuracy del 89%, mostrando que existe una relación no lineal entre las características y la vida útil restante. Esto confirma que los modelos de árboles son más adecuados para este dominio.

A pesar del alto desempeño, es importante interpretar estos resultados con cautela debido al tamaño reducido del conjunto de prueba. Con más datos reales podrían esperarse métricas más moderadas y un comportamiento más representativo del entorno operativo.

## **10.3 - Comparación de Métricas entre Modelos Optimizados**

Para complementar la evaluación individual, se comparan los modelos optimizados utilizando métricas macro (precision, recall y F1-score macro).
Estas métricas promedian el desempeño entre todas las clases:

- long_life

- mid_life

- near_retirement

Esto es fundamental en problemas multiclase donde se busca un rendimiento equilibrado.

---

**Resumen de métricas comparativas:**

| Métrica               | Descripción                                     |
| --------------------- | ----------------------------------------------- |
| **Accuracy**          | Proporción total de aciertos                    |
| **Precision (macro)** | Qué tan precisas son las predicciones por clase |
| **Recall (macro)**    | Qué tan bien detecta cada clase el modelo       |
| **F1 (macro)**        | Promedio balanceado entre precisión y recall    |

---

**Interpretación general:**

- Los modelos Gradient Boosting y Random Forest obtuvieron las métricas macro más altas, confirmando su excelente desempeño en clasificación tabular.

- El modelo SVM, aunque sólido, muestra menor capacidad para separar correctamente las tres clases, lo cual es esperable dada su naturaleza menos flexible frente a relaciones no lineales.

- Las métricas macro corroboran que los modelos basados en árboles son los más adecuados para estimar la vida útil restante de aeronaves en este dataset.

---

Los resultados muestran que los modelos optimizados clasifican de manera consistente las distintas categorías de vida útil, con Gradient Boosting y Random Forest como principales candidatos para la etapa de interpretabilidad y predicción final.
"""

# ============================================================
# 10.3 - Comparación de métricas entre modelos optimizados
# ============================================================

from sklearn.metrics import precision_score, recall_score, f1_score

# 1. Diccionario para almacenar métricas macro (promedio entre clases)
metricas = {
    "Modelo": [],
    "Accuracy": [],
    "Precision (macro)": [],
    "Recall (macro)": [],
    "F1 (macro)": []
}

# 2. Evaluación de cada modelo optimizado usando el conjunto de test
for nombre, modelo in mejores_modelos.items():
    pred = modelo.predict(X_test)

    metricas["Modelo"].append(nombre)
    metricas["Accuracy"].append(accuracy_score(y_test, pred))
    metricas["Precision (macro)"].append(
        precision_score(y_test, pred, average="macro")
    )
    metricas["Recall (macro)"].append(
        recall_score(y_test, pred, average="macro")
    )
    metricas["F1 (macro)"].append(
        f1_score(y_test, pred, average="macro")
    )

# 3. DataFrame con la comparación de métricas
df_metricas = pd.DataFrame(metricas)
df_metricas.set_index("Modelo", inplace=True)

print("📊 Comparación completa de métricas entre modelos:\n")
display(df_metricas)

# 4. Visualización del F1-macro, que resume el desempeño multiclase
plt.figure(figsize=(10,5))
sns.barplot(data=df_metricas.reset_index(), x="Modelo", y="F1 (macro)")
plt.title("F1-score Macro (promedio entre clases) - Comparación entre modelos")
plt.xticks(rotation=45)
plt.show()

"""# **11 - Interpretabilidad con SHAP**

La interpretabilidad es un componente clave en modelos de clasificación, especialmente cuando las predicciones impactan en mantenimiento, seguridad operacional o planificación de flota. Por ello, resulta fundamental entender cómo y por qué el modelo toma cada decisión.

En este proyecto se utiliza SHAP (SHapley Additive exPlanations), una técnica basada en teoría de juegos que permite:

- Explicar cada predicción indicando cuánto aporta cada variable.

- Identificar qué características aumentan o disminuyen la probabilidad de cada clase.

- Obtener explicaciones coherentes y localmente precisas, incluso en modelos complejos.

SHAP es adecuado para modelos basados en árboles (Random Forest, Gradient Boosting) mediante TreeSHAP, que ofrece explicaciones rápidas y exactas. Esto es especialmente valioso en el ámbito aeronáutico, donde la trazabilidad y la transparencia son fundamentales para justificar decisiones basadas en datos.
"""

# ============================================================
# 11 - Interpretabilidad SHAP
# ============================================================

# 1. Inicializa los componentes visuales interactivos de SHAP para Jupyter
shap.initjs()

# 2. Crea un explicador específico para modelos basados en árboles (TreeSHAP)
explainer = shap.TreeExplainer(mejor_modelo)

# 3. Calcula los valores SHAP para el conjunto de prueba
shap_values = explainer.shap_values(X_test)

# 4. Gráfico resumen tipo "barra": importancia global promedio de cada variable
shap.summary_plot(shap_values, X_test, plot_type="bar")

# 5. Gráfico resumen detallado: impacto, magnitud y distribución de cada feature
shap.summary_plot(shap_values, X_test)

"""Los gráficos SHAP permiten identificar qué variables tienen mayor impacto en las predicciones del modelo y cómo influyen en la clasificación de long_life, mid_life y near_retirement.

La importancia global se mide con el SHAP Bar Summary, que muestra que las variables más influyentes fueron:

- edad_aeronave — principal indicador de desgaste y ciclo de vida.

- tipo_motor_TURBOPROP — asociado a operaciones más intensivas.


Por otro lado, el impacto por valor de cada variable se puede medir con el SHAP Summary, donde se observa que:

- edad_aeronave: valores altos tienden a empujar las predicciones hacia near_retirement, mientras que valores bajos favorecen long_life.

- tipo_motor_TURBOPROP: incrementa la probabilidad de pertenecer a clases con menor vida útil restante.

- Líneas de producción: ciertas familias (p. ej., Bombardier CRJ-100/2 o Boeing 737 Classic) muestran patrones asociados a mayor envejecimiento operativo.

En conjunto, SHAP permite validar el modelo y comprender cómo cada variable contribuye a la decisión final, aportando transparencia y trazabilidad al proceso predictivo.

# **12 - Implementación del Modelo Final y Visualización de Resultados**

Una vez seleccionado el mejor modelo (Random Forest), es momento de demostrar cómo puede utilizarse para apoyar la toma de decisiones sobre el estado operativo de las aeronaves.

Este bloque final muestra:

- Cómo realizar predicciones sobre nuevos datos.

- Cómo interpretar los resultados a nivel global (SHAP) y a nivel individual.

- Cómo visualizar el desempeño del modelo de forma clara y accionable.
"""

# ============================================================
# 12 - IMPLEMENTACIÓN DEL MODELO FINAL (VERSIÓN ESTABLE)
# ============================================================

import matplotlib.pyplot as plt
import seaborn as sns
import shap
import numpy as np
from sklearn.metrics import confusion_matrix

shap.initjs()

# ------------------------------------------
# Dataset original + procesado
# ------------------------------------------

df_original = df_limpio.copy()
X_processed = X_scaled_df
X_test_processed = X_scaled_df.loc[X_test_df.index]

# ------------------------------------------
# Selección de aeronaves reales
# ------------------------------------------

nuevas_idxs = X_test_processed.sample(5, random_state=42).index
aeronaves_originales = df_original.loc[nuevas_idxs].copy()

predicciones = mejor_modelo.predict(X_test_processed.loc[nuevas_idxs])
aeronaves_originales["Predicción RUL"] = predicciones

display(aeronaves_originales)

# ------------------------------------------
# Distribución de predicciones
# ------------------------------------------

plt.figure(figsize=(7,4))
sns.countplot(x=predicciones, palette="viridis")
plt.title("Distribución de predicciones del modelo final")
plt.xlabel("Categoría RUL")
plt.ylabel("Cantidad")
plt.show()

"""# **13 - Conclusiones del Modelo**

El desarrollo de este proyecto permitió transformar datos aeronáuticos abiertos en un sistema predictivo capaz de estimar la vida útil restante (RUL) de una aeronave, clasificándola en tres estados operativos:

- long_life – aeronaves con amplio horizonte de operación.

- mid_life – aeronaves en etapa intermedia.

- near_retirement – aeronaves cercanas al retiro o en estado avanzado de uso.

Tras el proceso de ingeniería de atributos, validación cruzada y optimización de hiperparámetros, el modelo con mejor desempeño fue Gradient Boosting, seguido muy de cerca por Random Forest.

Estos modelos lograron capturar con precisión patrones estructurales presentes en el dataset, destacándose por su capacidad de modelar relaciones no lineales y de alta interacción entre variables clave como:

- edad de la aeronave.

- tipo de motor.

- línea de producción.

- configuraciones específicas asociadas a familias de aeronaves.

Los resultados obtenidos sobre el conjunto de test muestran un desempeño consistente, validado mediante métricas como accuracy, matriz de confusión y F1-score.

La utilización de SHAP (Shapley Additive Explanations) permitió comprender de manera transparente cómo cada variable influye en la predicción final, reforzando la trazabilidad y credibilidad del modelo—un aspecto fundamental en contextos aeronáuticos donde la seguridad y la auditabilidad son requisitos esenciales.

---

El sistema predictivo construido puede integrarse como herramienta de apoyo para:

- Gestión estratégica de flota: Identificar familias de aeronaves con mayor o menor proyección operativa.

- Planificación de mantenimiento: Priorizar aeronaves cercanas al ciclo de retiro o con comportamientos operativos críticos.

- Análisis financiero y de reemplazo: Estimar ventanas de inversión para renovación de flota o venta de activos.

- Evaluación de riesgo operacional: Comprender el envejecimiento relativo de la flota con criterios cuantitativos.

Este trabajo demuestra que, a partir de datos abiertos y técnicas modernas de Machine Learning, es posible construir un modelo explicable y potencialmente integrable en sistemas de mantenimiento y planificación aeronáutica.
"""